#!/bin/bash

mkcd() {
    if [ $# != 1  ]; then
        echo "Usage: mkcd <dir>"
    else
        mkdir -p $1 && cd $1
    fi
}

mkcdl(){
    if [ $# != 1  ]; then
        echo "Usage: mkcdl <dir>"
    else
        mkdir -p $1 && cd $1 && ls
    fi
}

cdl(){
    if [ $# != 1  ]; then
        echo "Usage: cdl <dir>"
    else
        cd $1 && ls
    fi
}


cl()
{
    last_dir="$(ls -Frt | grep '/$' | tail -n1)"
    if [ -d "$last_dir"  ]; then
        cd "$last_dir"
    fi
}

extract () 
{ 
    local x
    ee() { 
            echo "$@"
            $1 "$2"
        }
    for x in "$@"; do
        [[ -f $x  ]] || continue
        case "$x" in
            *.tar.bz2 | *.tbz2 )    ee "tar xvjf" "$x"   ;;
            *.tar.gz | *.tgz )      ee "tar xvzf" "$x"   ;;
            *.bz2 )                 ee "bunzip2" "$x"    ;;
            *.rar )                 ee "unrar x" "$x"    ;;
            *.gz )                  ee "gunzip" "$x"     ;;
            *.tar )                 ee "tar xvf" "$x"    ;;
            *.zip )                 ee "unzip" "$x"      ;;
            *.Z )                   ee "uncompress" "$x" ;;
            *.7z )                  ee "7z x" "$x"       ;;
        esac
    done
}

function mark() {
  if [ $# -eq 1 ]; then
      echo "alias $1='cd `pwd`'" >> ~/unix/bash/alias_personal;
      source "$HOME/.bashrc";
  fi
}

